# Generated by Django 5.0.2 on 2024-02-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('block', models.CharField(max_length=10)),
                ('slots', models.CharField(max_length=10)),
            ],
        ),
    ]
