# Generated by Django 5.0.2 on 2024-02-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='slots',
            name='free',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
