# Generated by Django 5.0.2 on 2024-02-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_slots_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slots',
            name='free',
            field=models.CharField(default='Yes', max_length=10),
        ),
    ]
