# Generated by Django 5.0.2 on 2024-02-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_slots_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slots',
            name='free',
            field=models.CharField(max_length=10),
        ),
    ]
