# Generated by Django 5.0.2 on 2024-02-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_slots_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='slots',
            name='free',
            field=models.CharField(default='Yes', max_length=10),
            preserve_default=False,
        ),
    ]
