# Generated by Django 5.0.2 on 2024-02-26 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_slots_free'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slots',
            name='free',
        ),
    ]
