# Generated by Django 5.0.2 on 2024-02-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_slots_free'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=50)),
                ('slot_no', models.CharField(max_length=10)),
                ('free', models.CharField(max_length=10)),
            ],
        ),
    ]
