# Generated by Django 5.0.2 on 2024-02-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_childslots'),
    ]

    operations = [
        migrations.AddField(
            model_name='childslots',
            name='type',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
