# Generated by Django 5.0.2 on 2024-02-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_childslots_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='entry_date_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='exit_date_time',
            field=models.CharField(max_length=50),
        ),
    ]
