# Generated by Django 5.0.2 on 2024-02-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_bookings_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='childslots',
            name='ticket_no',
            field=models.CharField(default='', max_length=100),
        ),
    ]
