# Generated by Django 5.0.2 on 2024-02-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='price',
            field=models.CharField(default='', max_length=10),
        ),
    ]
